const omelette = require('omelette');
const { ACTIONS } = require('./enums/actions.enum');

const setupAutocomplete = () => {
  const completion = omelette('nitor|nu');

  // Define the completion tree
  completion.tree({
    [ACTIONS.BUILD]: {
      '-project': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-p': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-components': ['client', 'administration', 'provider', 'rest-api'],
      '-c': ['client', 'administration', 'provider', 'rest-api'],
      '-instance': ['dev', 'qa', 'pilot'],
      '-i': ['dev', 'qa', 'pilot'],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.DEPLOY]: {
      '-project': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-p': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-components': ['client', 'administration', 'provider', 'rest-api'],
      '-c': ['client', 'administration', 'provider', 'rest-api'],
      '-instance': ['dev', 'qa', 'pilot'],
      '-i': ['dev', 'qa', 'pilot'],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.BUILD_DEPLOY]: {
      '-project': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-p': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-components': ['client', 'administration', 'provider', 'rest-api'],
      '-c': ['client', 'administration', 'provider', 'rest-api'],
      '-instance': ['dev', 'qa', 'pilot'],
      '-i': ['dev', 'qa', 'pilot'],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.CREATE_BRANCH]: {
      '-task': [],
      '-t': [],
      '-type': ['feat', 'fix'],
      '-ty': ['feat', 'fix'],
      '-description': [],
      '-d': [],
      '-project': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-p': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.REVIEW]: {
      '-project': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-p': [
        'portal',
        'gateway',
        'phr',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-mergeId': [],
      '-mId': [],
      '-repository': [
        'portalClient',
        'portalBackend',
        'portalDeployment',
        'portalAutomation',
        'gatewayBackend',
        'gatewayClient',
        'gatewayDeployment',
        'phrClient',
        'phrBackend',
        'phrDeployment',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-r': [
        'portalClient',
        'portalBackend',
        'portalDeployment',
        'portalAutomation',
        'gatewayBackend',
        'gatewayClient',
        'gatewayDeployment',
        'phrClient',
        'phrBackend',
        'phrDeployment',
        'configService',
        'healthRecords',
        'centralAuth',
        'mpi',
        'phrAdminBackend',
        'phrAdminClient',
        'terminologyService',
      ],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.REFACTOR]: {
      '-help': [],
      '--h': [],
    },
    [ACTIONS.BACKUP]: {
      '-project': ['configService', 'medicaCentralAuth', 'medicaPortal', 'phr'],
      '-p': ['configService', 'medicaCentralAuth', 'medicaPortal', 'phr'],
      '-components': [],
      '-c': [],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.MERGE]: {
      '-source': [],
      '-s': [],
      '-target': [],
      '-ta': [],
      '-help': [],
      '--h': [],
    },
    [ACTIONS.CLEANUP]: {
      '-help': [],
      '--h': [],
    },
    [ACTIONS.VERSION]: [],
    [ACTIONS.HELP]: [],
  });

  // Initialize the completion
  completion.init();

  return completion;
};

module.exports = { setupAutocomplete };
